---
title: "TUGAS PRAKTIKUM INDIVIDU MODUL 4"
author: "Andrian Agusitinus Lumban Gaol"
date: "2023-12-05"
output:
  word_document: default
  html_document: default
---

# TUGAS
## 1. Buatlah Tabel Perkalian sampai 10
```{r}
# Fungsi untuk membuat tabel perkalian hingga suku ke-n
tabel_perkalian <- function(n) {
  # Menampilkan judul tabel
  cat("Tabel Perkalian", n, ":\n")
  
  # Loop untuk iterasi baris
  for (i in 1:n) {
    # Loop untuk iterasi kolom (hingga 10)
    for (j in 1:10) {
      # Menghitung hasil perkalian
      hasil <- i * j
      
      # Menampilkan hasil perkalian dalam format yang sesuai
      cat(i, "x", j, "=", hasil, "\t")
    }
    
    # Pindah ke baris berikutnya setelah satu baris selesai
    cat("\n")
  }
}

# Memanggil fungsi untuk membuat tabel perkalian hingga suku ke-10
tabel_perkalian(10)

```

## 2. Buatlah suatu fungsi yang menampilkan formulasi pendugaan nilai z (jumlah derat tak hingga) sebagai berikut
$$ z= 1+ \frac{5}{6}+ \frac{7}{11}+ \frac{9}{18}+ ...$$
```{r}
# Fungsi untuk menghitung nilai z
calculate_z <- function(n) {
  # Inisialisasi nilai awal z
  z <- 1
  
  # Loop untuk menghitung nilai z hingga suku ke-n
  for (i in 2:n) {
    # Penambahan suku ke-n sesuai pola
    z <- z + (2*i + 1)/(3*i + 5)
  }
  
  return(z)
}

# Menampilkan hasil perhitungan nilai z untuk suku ke-n (misal, n = 10)
n_value <- 10
result <- calculate_z(n_value)

# Menampilkan hasil
cat("Nilai z untuk suku ke-", n_value, "adalah:", result)

```

## 3. Berapa nilai ð‘“(7) berdasarkan fungsi rekursif berikut (tunjukkan urutan perhitungannya):
$$ F(n) = 
\begin{cases}
    n+1 & \text{jika } n = 1 \\
    2+f(n-1), & \text{jika } n = 2 \\
    \sum^{n}_{k=2}{f(k-1)+f(n-k+1)}  & \text{jika } n > 2
\end{cases}
$$
```{r}
# Fungsi rekursif f dengan parameter n
f <- function(n){
  # Kasus dasar: jika n = 1, kembalikan nilai (n + 1)
  if(n == 1){
    return(n + 1)
  }
  # Kasus khusus untuk n = 2
  else if(n == 2){
    # Kembalikan nilai 2 ditambah dengan hasil rekursif f(n-1)
    return(2 + f(n-1))
  }
  # Kasus umum untuk n > 2
  else{
    # Inisialisasi vektor kosong untuk elemen-elemen di sebelah kiri dan kanan
    vektor_kiri <- c()
    vektor_kanan <- c()
    
    # Loop untuk mengisi vektor_kiri dan vektor_kanan
    for (k in 2:n) {
      vektor_kiri <- append(vektor_kiri, f(k-1))
      vektor_kanan <- append(vektor_kanan, f(n-k+1))
    }
    
    # Kembalikan hasil penjumlahan elemen-elemen vektor_kiri dan vektor_kanan
    return(sum(vektor_kiri + vektor_kanan))
  }
}

# Memanggil fungsi f dengan parameter n = 7
result <- f(7)
cat("Hasil f(7) adalah:", result)

```



